### ISSUE TITLE
Error starting Python MM

### ISSUE THREAD

**Issue by WilliamJamesDalrympleWest** [HackerHouseYT/AI-Smart-Mirror#11]
SyntaxError: invalid syntax
NA-3:AI-Smart-Mirror w$ python bot.py
Traceback (most recent call last):
  File "bot.py", line 7, in <module>
    import requests
ImportError: No module named requests
NA-3:AI-Smart-Mirror w$

**Comment by WilliamJamesDalrympleWest** [comment]
^
SyntaxError: invalid syntax
NA-3:AI-Smart-Mirror w$ python bot.py
Traceback (most recent call last):
  File "bot.py", line 7, in <module>
    import requests
ImportError: No module named requests
NA-3:AI-Smart-Mirror w$ source hhsmartmirror/bin/activate
(hhsmartmirror) NA-3:AI-Smart-Mirror w$ python bot.py
/Users/w/AI-Smart-Mirror/hhsmartmirror/lib/python2.7/site-packages/pydub/utils.py:178: RuntimeWarning: Couldn't find ffplay or avplay - defaulting to ffplay, but may not work
  warn("Couldn't find ffplay or avplay - defaulting to ffplay, but may not work", RuntimeWarning)
Warning: OpenCV not installed. To use facial recognition, make sure you've properly configured OpenCV.
Found face
Traceback (most recent call last):
  File "bot.py", line 254, in <module>
    bot.start()
  File "bot.py", line 43, in start
    recognizer, audio = self.speech.listen_for_audio()
  File "/Users/w/AI-Smart-Mirror/speech.py", line 32, in listen_for_audio
    m = sr.Microphone()
  File "/Users/w/AI-Smart-Mirror/hhsmartmirror/lib/python2.7/site-packages/speech_recognition/__init__.py", line 56, in __init__
    self.pyaudio_module = self.get_pyaudio()
  File "/Users/w/AI-Smart-Mirror/hhsmartmirror/lib/python2.7/site-packages/speech_recognition/__init__.py", line 86, in get_pyaudio
    raise AttributeError("Could not find PyAudio; check installation")
AttributeError: Could not find PyAudio; check installation
(hhsmartmirror) NA-3:AI-Smart-Mirror w$

**Comment by muratia** [comment]
Try installing PyAudio using pip

python -m pip install pyaudio

**Comment by muratia** [comment]
http://www.pyimagesearch.com/2015/06/15/install-opencv-3-0-and-python-2-7-on-osx/

**Comment by WilliamJamesDalrympleWest** [comment]
Many thanks
