### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by ganjaaa** [HackerHouseYT/AI-Smart-Mirror#21]
```
╭─root@CrankBox  /opt/AI-Smart-Mirror  ‹master*›
╰─# source hhsmartmirror/bin/activate 
(hhsmartmirror) ╭─root@CrankBox  /opt/AI-Smart-Mirror  ‹master*›
╰─# python bot.py
Traceback (most recent call last):
  File "bot.py", line 12, in <module>
    from nlg import NLG
  File "/opt/AI-Smart-Mirror/nlg.py", line 7, in <module>
    gateway = launch_py4j_server()
  File "/opt/AI-Smart-Mirror/py4j_server/__init__.py", line 31, in launch_py4j_server
    stdout=PIPE, stdin=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

OS Debian Jessie , all stable and updated

**Comment by ewaldHertel** [comment]
I have the same problem. My os is Ubuntu 16.04 LTS all uptodate.

**Comment by atainter** [comment]
AI-Smart-Mirror is not supported on Ubuntu.
