### ISSUE TITLE
After "ok mirror" the whole process stops! (MacOS Sierra 10.12.2)

### ISSUE THREAD

**Issue by activea** [HackerHouseYT/AI-Smart-Mirror#25]
I'm listening
Found audio
Traceback (most recent call last):
  File "bot.py", line 254, in <module>
    bot.start()
  File "bot.py", line 44, in start
    if self.speech.is_call_to_action(recognizer, audio):
  File "/Users/activea/Desktop/AI-Smart-Mirror-master/speech.py", line 44, in is_call_to_action
    speech = self.google_speech_recognition(recognizer, audio)
  File "/Users/activea/Desktop/AI-Smart-Mirror-master/speech.py", line 20, in google_speech_recognition
    speech = recognizer.recognize_google(audio)
  File "/Users/activea/Desktop/AI-Smart-Mirror-master/hhsmartmirror/lib/python2.7/site-packages/speech_recognition/__init__.py", line 741, in recognize_google
    best_hypothesis = max(actual_result["alternative"], key=lambda alternative: alternative["confidence"])
  File "/Users/activea/Desktop/AI-Smart-Mirror-master/hhsmartmirror/lib/python2.7/site-packages/speech_recognition/__init__.py", line 741, in <lambda>
    best_hypothesis = max(actual_result["alternative"], key=lambda alternative: alternative["confidence"])
KeyError: 'confidence'

**Comment by rayzsoul** [comment]
Hi, I have the same error. How did you fix it?
