### ISSUE TITLE
KeyError: 'minutely'

### ISSUE THREAD

**Issue by rayzsoul** [HackerHouseYT/AI-Smart-Mirror#27]
Hi,

The mirror keeps failing to understand the weather intent.
Do you know how to fix KeyError: 'minutely'?

Thanks!

--
I'm listening
Found audio
Google Speech Recognition thinks you said how's the weather like today
{
  "msg_id" : "204ad351-2b59-4edc-bdda-f418438d8100",
  "_text" : "how's the weather like today",
  "entities" : {
    "datetime" : [ {
      "confidence" : 0.9965476720505433,
      "values" : [ {
        "value" : "2017-02-01T00:00:00.000-08:00",
        "grain" : "day",
        "type" : "value"
      } ],
      "value" : "2017-02-01T00:00:00.000-08:00",
      "grain" : "day",
      "type" : "value"
    } ],
    "Intent" : [ {
      "confidence" : 0.9993092979476336,
      "value" : "weather"
    } ]
  }
}
weather
Failed wit!
'minutely'
Traceback (most recent call last):
  File "bot.py", line 79, in decide_action
    self.__weather_action(entities)
  File "bot.py", line 174, in __weather_action
    weather_obj = self.knowledge.find_weather()
  File "/Users/1100192/Desktop/RayzSmartMirror/AI-Smart-Mirror/knowledge.py", line 25, in find_weather
    hourly_forecast = weather_json['minutely']['summary']
KeyError: 'minutely'

**Comment by mirekcerny** [comment]
I found this conversation: https://github.com/wit-ai/wit/issues/230
It seems that a new user session ID shall be used for wit.ai when restarting the conversation.
I however don't know how to fix the code..

**Comment by vigneshmanikandan97** [comment]
Google Speech Recognition thinks you said **show me the 7 day weather forecast**
{"_text":"show me the 7 day weather forecast","entities":{"Map_Type":[{"confidence":1,"value":"show","type":"value"}],"Weather_Type":[{"confidence":0.84525911283765,"value":"7 day","type":"value"}],"Intent":[{"confidence":0.99989721680768,"value":"weather"}]},"msg_id":"0p6oX0qOkRoNtYxiw"}
weather
Failed wit!
'minutely'
Traceback (most recent call last):
  File "bot.py", line 78, in decide_action
    self.__weather_action(entities)
  File "bot.py", line 173, in __weather_action
    weather_obj = self.knowledge.find_weather()
  File "/home/vignesh/Documents/github/AI-Smart-Mirror-master/knowledge.py", line 25, in find_weather
    hourly_forecast = weather_json['minutely']['summary']
KeyError: 'minutely'
^CTraceback (most recent call last):
  File "bot.py", line 254, in <module>
    bot.start()
  File "bot.py", line 46, in start
    self.decide_action()
  File "bot.py", line 112, in decide_action
    self.decide_action()
  File "bot.py", line 109, in decide_action
    self.__text_action("I'm sorry, I couldn't understand what you meant by that")
  File "bot.py", line 154, in __text_action
    self.speech.synthesize_text(text)
  File "/home/vignesh/Documents/github/AI-Smart-Mirror-master/speech.py", line 55, in synthesize_text
    play(song)
  File "/home/vignesh/Documents/github/AI-Smart-Mirror-master/hhsmartmirror/lib/python2.7/site-packages/pydub/playback.py", line 44, in play
    _play_with_pyaudio(audio_segment)
  File "/home/vignesh/Documents/github/AI-Smart-Mirror-master/hhsmartmirror/lib/python2.7/site-packages/pydub/playback.py", line 33, in _play_with_pyaudio
    stream.write(chunk._data)
  File "/home/vignesh/Documents/github/AI-Smart-Mirror-master/hhsmartmirror/lib/python2.7/site-packages/pyaudio.py", line 586, in write
    exception_on_underflow)

How do I create new Session IDs as mentioned above in your reply? 
A link or a sample piece of code would be really helpful.
Thank You.
