### ISSUE TITLE
'utf8' codec can't decode byte 0x8b in position 1: invalid start byte

### ISSUE THREAD

**Issue by nicolasfraikin** [HackerHouseYT/AI-Smart-Mirror#35]
I´ve been running AI-Smart-Mirror together with Magic Mirror for quite some time now but since two days or so it doens´t work anymore and collapses after it recognized audio the first time. It somehow has a problem with Google Speech Recognition and decoding my text I guess but I didn´t change anything so I really don´t know what it is. Maybe someone else had similar problems?
Thanks in advance!

Here´s the error:

I'm listening
Found audio
Traceback (most recent call last):
  File "bot.py", line 500, in <module>
    bot.start()
  File "bot.py", line 52, in start
    if self.speech.is_call_to_action(recognizer, audio):
  File "/Users/nicolasfraikin/Documents/Raspberry_Pi_Projekte/Project_Smart_Mirror/AI-Smart-Mirror-master/speech.py", line 44, in is_call_to_action
    speech = self.google_speech_recognition(recognizer, audio)
  File "/Users/nicolasfraikin/Documents/Raspberry_Pi_Projekte/Project_Smart_Mirror/AI-Smart-Mirror-master/speech.py", line 20, in google_speech_recognition
    speech = recognizer.recognize_google(audio, language="de")
  File "/Users/nicolasfraikin/Documents/Raspberry_Pi_Projekte/Project_Smart_Mirror/AI-Smart-Mirror-master/hhsmartmirror/lib/python2.7/site-packages/speech_recognition/__init__.py", line 725, in recognize_google
    response_text = response.read().decode("utf-8")
  File "/Users/nicolasfraikin/Documents/Raspberry_Pi_Projekte/Project_Smart_Mirror/AI-Smart-Mirror-master/hhsmartmirror/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by koshyviv** [comment]
Can you check the output of the following?

`speech = recognizer.recognize_google(audio, language="de",show_all=True)`
