### ISSUE TITLE
No response from AI after launch phrase

### ISSUE THREAD

**Issue by samsonlokxdd** [HackerHouseYT/AI-Smart-Mirror#43]
Google Speech Recognition thinks you said ok mirror
Found face
I'm listening
Found audio
Google Speech Recognition thinks you said ok mirror
Found face
I'm listening

**Comment by itwasallalim** [comment]
I am having the same problem

**Comment by YogiRaspi** [comment]
i am having the same issue that no response ..

**Comment by raghavpatnecha** [comment]
That's not an issue with the mirror. You need a fast internet connection because there are lots of API calls going on in the backend.

**Comment by aak2003** [comment]
Try rebooting the mirror software

**Comment by cowboysdude** [comment]
Yeah that's not working........it shows the output on the terminal window but never answers or shows anything.

**Comment by akshaybahadur21** [comment]
There's a problem with your alsa not with the mirror. Try updating it or changing the default sound card from options

**Comment by cowboysdude** [comment]
Options?  My computer sees it, the terminal window reports seeing it..... where is the 'options' to change it?
Thank you

**Comment by akshaybahadur21** [comment]
are you running Ubuntu on virtual box?

**Comment by cowboysdude** [comment]
I am running just Unbuntu no virtual box.  I have also tried running MM on serveronly mode but that doesn't work either

**Comment by akshaybahadur21** [comment]
Okay, So I am running it on Virtual Box. In that there is an option where you can configure the sound from default to intel HD

**Comment by cowboysdude** [comment]
OHhhhhhhhh Okay...well not sure what is going on here but I'm getting responses from terminal window in MM and the bot.py file but nothing shows on MM.....not getting text or audio.....

**Comment by akshaybahadur21** [comment]
Can you post a screenshot of your terminal?
If there is a sound problem then you might want to try this:
sudo apt-get install alsa-utils --reinstall
./configure && make
sudo make install
 sudo alsa force-reload

Or 
sudo apt-get install ubuntu-restricted-extras

**Comment by cowboysdude** [comment]
getting this when trying to run alsomixer.......

           ALSA lib conf.c:1028:(parse_value) card is not a string
ALSA lib conf.c:1697:(snd_config_load1) _toplevel_:2:0:Invalid argument
ALSA lib conf.c:3449:(config_file_open) /etc/asound.conf may be old or corrupted: consider to remove or fix it
ALSA lib conf.c:3371:(snd_config_hooks_call) function snd_config_hook_load returned error: Invalid argument
ALSA lib conf.c:3820:(snd_config_update_r) hooks failed, removing configuration
cannot open mixer: Invalid argument

**Comment by cowboysdude** [comment]
Opps okay got that working had the wrong device LOL

**Comment by cowboysdude** [comment]
`ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.USB-Audio.pcm.hdmi.0:CARD=1,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM hdmi
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.USB-Audio.pcm.hdmi.0:CARD=1,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM hdmi
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.USB-Audio.pcm.modem.0:CARD=1'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline:CARD=1,DEV=0
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.USB-Audio.pcm.modem.0:CARD=1'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline:CARD=1,DEV=0
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.USB-Audio.pcm.modem.0:CARD=1'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM phoneline
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.USB-Audio.pcm.modem.0:CARD=1'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM phoneline
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
I'm listening
Found audio
Google Speech Recognition could not understand audio
Found face
I'm listening
Found audio
Google Speech Recognition thinks you said weather
Found face
I'm listening
Found audio
Google Speech Recognition thinks you said show me the weather
Found face
I'm listening
Found audio
Google Speech Recognition could not understand audio
Found face
I'm listening
Found audio
Google Speech Recognition could not understand audio
Found face
I'm listening
`

**Comment by cowboysdude** [comment]
Appreciate all your help but this just doesn't work...... I have just installed another AI that works right out of the box without all these issues....... Thank you again but I deleted this......it's no good.

**Comment by vigneshmanikandan97** [comment]
Which other AI did you resort to in the end?
If it is an open source AI, can you please drop a link to it?
Thanks.

**Comment by akshaybahadur21** [comment]
I used the Hacker House one only. Will be uploading the code to GitHub soon. To get an idea of how my project look like you can refer to this video: https://www.youtube.com/watch?v=FZ486L4r7Bs&t=24s

**Comment by vigneshmanikandan97** [comment]
I am currently using their AI code but I get a KeyError issue in the **bot.py**   code.
I watched that video sometime back and it is quite impressive what you're doing here. 
Thanks for the help.

**Comment by akshaybahadur21** [comment]
Can you explain your error in detail? If possible post a screenshot of the terminal. Also tell the specs of your OS

**Comment by vigneshmanikandan97** [comment]
# Error message on console

I'm listening
Found audio
Google Speech Recognition thinks you said what is the current weather
{"_text":"what is the current weather","entities":{"Intent":[{"confidence":0.98898134537505,"value":"weather"}],"Weather_Type":[{"confidence":0.88768633105406,"value":"current"}]},"msg_id":"0oKpEAE5qSVaglRIF"}
weather
Failed wit!
'minutely'
Traceback (most recent call last):
  File "bot.py", line 78, in decide_action
    self.__weather_action(entities)
  File "bot.py", line 173, in __weather_action
    weather_obj = self.knowledge.find_weather()
  File "/home/vignesh/Documents/github/AI-Smart-Mirror-master/knowledge.py", line 25, in find_weather
    hourly_forecast = weather_json['minutely']['summary']
KeyError: 'minutely'

**Screenshot of the Terminal**

![error_msg](https://user-images.githubusercontent.com/30258353/35563248-1dc5c69e-05dc-11e8-9f37-47a1f20f30d0.png)


**Screenshot of my PC/OS specs**
![pc_details](https://user-images.githubusercontent.com/30258353/35563281-3469ac94-05dc-11e8-8617-fa65b29d2507.png)

**Comment by akshaybahadur21** [comment]
obviously, you will get a key error because there is no key named minutely. Even I encountered the same error. What you need to do is open knowledge.py and comment that line and wherever minutely key used.
Simple enough I guess
