### ISSUE TITLE
Getting error after launch phrase 

### ISSUE THREAD

**Issue by rajuking06** [HackerHouseYT/AI-Smart-Mirror#5]
`Google Speech Recognition thinks you said ok
Traceback (most recent call last):
  File "bot.py", line 254, in <module>
    bot.start()
  File "bot.py", line 45, in start
    self.__acknowledge_action()
  File "bot.py", line 143, in __acknowledge_action
    self.__text_action(self.nlg.acknowledge())
  File "bot.py", line 154, in __text_action
    self.speech.synthesize_text(text)
  File "/Users/sandeeprajup/Desktop/Smart-Mirror-AI/AI-Smart-Mirror/speech.py", line 54, in synthesize_text
    song = AudioSegment.from_mp3("tmp.mp3")
  File "/Users/sandeeprajup/Desktop/Smart-Mirror-AI/AI-Smart-Mirror/hhsmartmirror/lib/python2.7/site-packages/pydub/audio_segment.py", line 460, in from_mp3
    return cls.from_file(file, 'mp3')
  File "/Users/sandeeprajup/Desktop/Smart-Mirror-AI/AI-Smart-Mirror/hhsmartmirror/lib/python2.7/site-packages/pydub/audio_segment.py", line 443, in from_file
    p = subprocess.Popen(conversion_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
(hhsmartmirror) MacBook-Pro:AI-Smart-Mirror sandeeprajup$ `

**Comment by atainter** [comment]
It looks like it's not able to write/read a `tmp.mp3` file to your directory. Maybe try running with `sudo`.

**Comment by rajuking06** [comment]
Hi @atainter Thanks for the help. 

I tried troubleshoot by uninstall the ffmpeg. after reinstalling the ffmpeg i found an warning saying brew link ffmpeg issues. so have added write/read for the folder in the warning message. is **usr/local/......**. now AI-Smart-Mirror is working good. no issues now i will try to setup the Setup Facial Recognition.

Thanks again for bring this wonderful AI project.
