### ISSUE TITLE
error with wit.ai

### ISSUE THREAD

**Issue by danhajduk** [HackerHouseYT/AI-Smart-Mirror#60]
i get the following error on every phrase :

I'm listening
Found audio
Google Speech Recognition thinks you said hello
{"error":"Bad auth, check token\/params","code":"no-auth"}
None
Failed wit!
[Errno 2] No such file or directory
Traceback (most recent call last):
  File "bot.py", line 102, in decide_action
    self.__text_action("I'm sorry, I don't know about that yet.")
  File "bot.py", line 154, in __text_action
    self.speech.synthesize_text(text)
  File "/home/smartmiror/AI-Smart-Mirror/speech.py", line 54, in synthesize_text
    song = AudioSegment.from_mp3("tmp.mp3")
  File "/home/smartmiror/AI-Smart-Mirror/hhsmartmirror/local/lib/python2.7/site-packages/pydub/audio_segment.py", line 522, in from_mp3
    return cls.from_file(file, 'mp3', parameters)
  File "/home/smartmiror/AI-Smart-Mirror/hhsmartmirror/local/lib/python2.7/site-packages/pydub/audio_segment.py", line 505, in from_file
    p = subprocess.Popen(conversion_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "bot.py", line 254, in <module>
    bot.start()
  File "bot.py", line 48, in start
    self.decide_action()
  File "bot.py", line 109, in decide_action
    self.__text_action("I'm sorry, I couldn't understand what you meant by that")
  File "bot.py", line 154, in __text_action
    self.speech.synthesize_text(text)
  File "/home/smartmiror/AI-Smart-Mirror/speech.py", line 54, in synthesize_text
    song = AudioSegment.from_mp3("tmp.mp3")
  File "/home/smartmiror/AI-Smart-Mirror/hhsmartmirror/local/lib/python2.7/site-packages/pydub/audio_segment.py", line 522, in from_mp3
    return cls.from_file(file, 'mp3', parameters)
  File "/home/smartmiror/AI-Smart-Mirror/hhsmartmirror/local/lib/python2.7/site-packages/pydub/audio_segment.py", line 505, in from_file
    p = subprocess.Popen(conversion_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

on magic mirror it says : "I'm sorry, I couldn't understand what you meant by that"

**Comment by aak2003** [comment]
Your token should be passed along with the word "Bearer"

**Comment by aak2003** [comment]
Sorry pasted not passed in the file

**Comment by Triippz** [comment]
I seem to having the same issue, I have done the correct pasting. Seems to be a Wit.Ai issue.
