### ISSUE TITLE
getting error when trying to start bot.py

### ISSUE THREAD

**Issue by cybermritunjay** [HackerHouseYT/AI-Smart-Mirror#66]
Traceback (most recent call last):
  File "bot.py", line 12, in <module>
    from nlg import NLG
  File "/home/flux/MagicMirror/AI-Smart-Mirror/nlg.py", line 7, in <module>
    gateway = launch_py4j_server()
  File "/home/flux/MagicMirror/AI-Smart-Mirror/py4j_server/__init__.py", line 31, in launch_py4j_server
    stdout=PIPE, stdin=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by darshank26** [comment]
Even I got the same error can somebody got a solution for this error...

**Comment by darshank26** [comment]
@cybermritunjay did you got the solution for this problem?

**Comment by akshaybahadur21** [comment]
Are you guys deploying it in windows?

**Comment by cybermritunjay** [comment]
@darshank26 no bro

**Comment by cybermritunjay** [comment]
I m devloping it in ubuntu 17 @akshaybahadur21

**Comment by darshank26** [comment]
@akshaybahadur21 yes I'm using window

**Comment by akshaybahadur21** [comment]
this issue is common in windows. Try ubuntu
This issue is not in ubuntu 16

**Comment by cybermritunjay** [comment]
Got it solved

**Comment by Josh4you** [comment]
Hey, guys please help me out. I too get this error when I start the bot.py file.I am using linux Mint

**Comment by Josh4you** [comment]
Alright, so as per the code says in _int_.py file you need to have java in your System or OS. so install the latest version of JDK and JRE to solve this issue.

**Comment by darshank26** [comment]
@akshaybahadur21 is there no solution for windows system ???
