### ISSUE TITLE
Running bot.py

### ISSUE THREAD

**Issue by kk1775** [HackerHouseYT/AI-Smart-Mirror#76]
Hi, I follow the steps and run the bot.py and it shows this:
Error: Could not find or load main class Py4JServer
Traceback (most recent call last):
  File "bot.py", line 12, in <module>
    from nlg import NLG
  File "C:\Users\kk1775\Desktop\AI-Smart-Mirror-master\nlg.py", line 7, in <module>
    gateway = launch_py4j_server()
  File "C:\Users\kk1775\Desktop\AI-Smart-Mirror-master\py4j_server\__init__.py", line 34, in launch_py4j_server
    _port = int(_pid.stdout.readline())
ValueError: invalid literal for int() with base 10: ' '
What can I do to solve this? plz help me I'm appreciated

**Comment by killerPhoenix** [comment]
Try installing...java..

**Comment by kk1775** [comment]
Hi, I had java on my computer.
Is there any other way to solve this?

**Comment by killerPhoenix** [comment]
did u gave python bot.py  in virtualenv...try tht..it may work...

**Comment by Josh4you** [comment]
try installing py4js manually

**Comment by vikas12121200** [comment]
same error please help
```
(hhsmartmirror) pi@raspberrypi:~/AI-Smart-Mirror $ python bot.py
Traceback (most recent call last):
  File "bot.py", line 12, in <module>
    from nlg import NLG
  File "/home/pi/AI-Smart-Mirror/nlg.py", line 7, in <module>
    gateway = launch_py4j_server()
  File "/home/pi/AI-Smart-Mirror/py4j_server/__init__.py", line 31, in launch_py4j_server
    stdout=PIPE, stdin=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
