### ISSUE TITLE
opencv

### ISSUE THREAD

**Issue by killerPhoenix** [HackerHouseYT/AI-Smart-Mirror#78]
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /build/opencv-SviWsf/opencv-2.4.9.1+dfsg/modules/imgproc/src/color.cpp, line 3737
Traceback (most recent call last):
  File "bot.py", line 254, in <module>
    bot.start()
  File "bot.py", line 40, in start
    if self.vision.recognize_face():
  File "/home/jerin/project/AI-Smart-Mirror-master/vision.py", line 32, in recognize_face
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
cv2.error: /build/opencv-SviWsf/opencv-2.4.9.1+dfsg/modules/imgproc/src/color.cpp:3737: error: (-215) scn == 3 || scn == 4 in function cvtColor

**Comment by killerPhoenix** [comment]
can any one help me with this i dont hv time...plzzz help me fast.... 
:/
