### ISSUE TITLE
starting bot.py

### ISSUE THREAD

**Issue by alex11704** [HackerHouseYT/AI-Smart-Mirror#8]
Traceback (most recent call last):
  File "bot.py", line 12, in <module>
    from nlg import NLG
  File "/Users/interview6/Desktop/!mirror/AI-Smart-Mirror-master/nlg.py", line 4, in <module>
    from py4j_server import launch_py4j_server
  File "/Users/interview6/Desktop/!mirror/AI-Smart-Mirror-master/py4j_server/__init__.py", line 8, in <module>
    from py4j.java_gateway import JavaGateway, GatewayClient, java_import
ImportError: No module named py4j.java_gateway
(hhsmartmirror) alex:AI-Smart-Mirror-master interview6$ python bot.py 
Traceback (most recent call last):
  File "bot.py", line 12, in <module>
    from nlg import NLG
  File "/Users/interview6/Desktop/!mirror/AI-Smart-Mirror-master/nlg.py", line 4, in <module>
    from py4j_server import launch_py4j_server
  File "/Users/interview6/Desktop/!mirror/AI-Smart-Mirror-master/py4j_server/__init__.py", line 8, in <module>
    from py4j.java_gateway import JavaGateway, GatewayClient, java_import
ImportError: No module named py4j.java_gateway

**Comment by zgelici** [comment]
Hi,

I think the solution is:

run first this command:

source hhsmartmirror/bin/activate

**Comment by alex11704** [comment]
HI
I am getting this error now

Traceback (most recent call last):
  File "bot.py", line 7, in <module>
    import requests
ImportError: No module named requests

**Comment by fifacode** [comment]
Hi i have this error

Traceback (most recent call last):
  File "bot.py", line 12, in <module>
    from nlg import NLG
  File "/home/nik/AI-Smart-Mirror/nlg.py", line 7, in <module>
    gateway = launch_py4j_server()
  File "/home/nik/AI-Smart-Mirror/py4j_server/__init__.py", line 31, in launch_py4j_server
    stdout=PIPE, stdin=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory



Can someone help me?

**Comment by prashu03** [comment]
i have this error and i am stuck up here
can i get some help please 

Traceback (most recent call last):
File "bot.py", line 12, in
from nlg import NLG
File "/home/nik/AI-Smart-Mirror/nlg.py", line 7, in
gateway = launch_py4j_server()
File "/home/nik/AI-Smart-Mirror/py4j_server/init.py", line 31, in launch_py4j_server
stdout=PIPE, stdin=PIPE)
File "/usr/lib/python2.7/subprocess.py", line 711, in init
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory

Can someone help me?

**Comment by sohailshareef** [comment]
Traceback (most recent call last):
  File "bot.py", line 6, in <module>
    import requests
ImportError: No module named requests
 i am getting this error please help me i have college project.

**Comment by fullbright** [comment]
I realized that pyaudio was not installed correctly. I was getting an error when I run the setup.sh, at the pyaudio installation stage.
I had to install portaudio19-dev to solve the issue on my side.
sudo apt-get install portaudio19-dev

**Comment by sohailshareef** [comment]
Hello thanks for your help but I am getting problem in speech recognization installation. My pyaudio installed successfully and at the end while starting bot.py I am getting error like no module named request. I am in big trouble to submit this project in college.

**Comment by sapgreengem** [comment]
Is there any solution of this error. I am not finding any way to get rid of this
(hhsmartmirror) gem@gem-Aspire-V5-571G:~/asd/AI-Smart-Mirror$ **python bot.py**
Traceback (most recent call last):
  File "bot.py", line 12, in <module>
    from nlg import NLG
  File "/home/gem/asd/AI-Smart-Mirror/nlg.py", line 7, in <module>
    gateway = launch_py4j_server()
  File "/home/gem/asd/AI-Smart-Mirror/py4j_server/__init__.py", line 31, in launch_py4j_server
    stdout=PIPE, stdin=PIPE)
  **File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception**
OSError: [Errno 2] No such file or directory

**Comment by fullbright** [comment]
Hello I found a solution. can you make sure that Java is installed on your
system ?

I installed Java and it started working again.

**Comment by aak2003** [comment]
HI
I am getting this error 

Traceback (most recent call last):
File "bot.py", line 7, in 
import requests
ImportError: No module named requests

**Comment by amshoo** [comment]
plz did someone the solution
Traceback (most recent call last):
  File "bot.py", line 12, in <module>
    from nlg import NLG
  File "C:\Users\USER\desktop\my-git\nlg.py", line 4, in <module>
    from py4j_server import launch_py4j_server
  File "C:\Users\USER\desktop\my-git\py4j_server\__init__.py", line 8, in <module>
    from py4j.java_gateway import JavaGateway, GatewayClient, java_import
ModuleNotFoundError: No module named 'py4j.java_gateway'

**Comment by aak2003** [comment]
Try going to this site about the installation of py4j

http://py4j.sourceforge.net/install.html#install-instructions

**Comment by ChrisCampling** [comment]
#mac users:

pip2 install requests 

#than 'pip2 install' each module not found. If having issues with pip2 install try:

curl https://bootstrap.pypa.io/get-pip.py | python

**Comment by zmxsxyu** [comment]
> Hi i have this error
> 
> Traceback (most recent call last):
> File "bot.py", line 12, in 
> from nlg import NLG
> File "/home/nik/AI-Smart-Mirror/nlg.py", line 7, in 
> gateway = launch_py4j_server()
> File "/home/nik/AI-Smart-Mirror/py4j_server/**init**.py", line 31, in launch_py4j_server
> stdout=PIPE, stdin=PIPE)
> File "/usr/lib/python2.7/subprocess.py", line 711, in **init**
> errread, errwrite)
> File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
> raise child_exception
> OSError: [Errno 2] No such file or directory
> 
> Can someone help me?

I m getting the same error, did you manage to solve it ?
