### ISSUE TITLE
python bot.py not working

### ISSUE THREAD

**Issue by shawdavid** [HackerHouseYT/AI-Smart-Mirror#80]
Hello all,

I have had trouble getting the `python bot.py` command to work. When I run it i receive the following error: 
`Traceback (most recent call last):
  File "bot.py", line 8, in <module>
    import requests
ImportError: No module named requests
(hhsmartmirror) Davids-Mac-mini:AI-Smart-Mirror davidshaw$ python bot.py
Traceback (most recent call last):
  File "bot.py", line 8, in <module>
    import requests
ImportError: No module named requests`

Can someone please advise on what to do to resolve this issue.

**Comment by rachnov55** [comment]
pip install requests
