### ISSUE TITLE
No matching distribution found for pyaudio

### ISSUE THREAD

**Issue by anggahartono** [HackerHouseYT/AI-Smart-Mirror#83]
Hi guys, I have a problem when I run sudo ./setup.sh  , I already install python 2.7 and pyaudio 0.2.11 on my mac (Mac OSX sierra 10.12.6).

hartonos-MacBook-Air:AI-Smart-Mirror-master hartono$ sudo ./setup.sh
Password:
The directory '/Users/hartono/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/hartono/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: virtualenv in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (15.2.0)
New python executable in /Users/hartono/Documents/AI-Smart-Mirror/AI-Smart-Mirror-master/hhsmartmirror/bin/python
Installing setuptools, pip, wheel...done.
The directory '/Users/hartono/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
The directory '/Users/hartono/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: speechrecognition in ./hhsmartmirror/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: gtts in ./hhsmartmirror/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: py4j in ./hhsmartmirror/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: python-dateutil in ./hhsmartmirror/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: pydub in ./hhsmartmirror/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: feedparser in ./hhsmartmirror/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: numpy in ./hhsmartmirror/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: six in ./hhsmartmirror/lib/python2.7/site-packages (from gtts->-r requirements.txt (line 2))
Requirement already satisfied: requests in ./hhsmartmirror/lib/python2.7/site-packages (from gtts->-r requirements.txt (line 2))
Requirement already satisfied: gtts_token in ./hhsmartmirror/lib/python2.7/site-packages (from gtts->-r requirements.txt (line 2))
Requirement already satisfied: certifi>=2017.4.17 in ./hhsmartmirror/lib/python2.7/site-packages (from requests->gtts->-r requirements.txt (line 2))
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./hhsmartmirror/lib/python2.7/site-packages (from requests->gtts->-r requirements.txt (line 2))
Requirement already satisfied: idna<2.7,>=2.5 in ./hhsmartmirror/lib/python2.7/site-packages (from requests->gtts->-r requirements.txt (line 2))
Requirement already satisfied: urllib3<1.23,>=1.21.1 in ./hhsmartmirror/lib/python2.7/site-packages (from requests->gtts->-r requirements.txt (line 2))
/Users/hartono/Documents/AI-Smart-Mirror/AI-Smart-Mirror-master/hhsmartmirror/lib/python2.7/site-packages/pip/commands/install.py:194: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
The directory '/Users/hartono/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
The directory '/Users/hartono/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pyaudio
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pyaudio/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pyaudio/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pyaudio/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pyaudio/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)': /simple/pyaudio/
  Could not fetch URL https://pypi.python.org/simple/pyaudio/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/pyaudio/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",)) - skipping
  Could not find a version that satisfies the requirement pyaudio (from versions: )
No matching distribution found for pyaudio

and then when i run python bot.py , i get this error
(hhsmartmirror) hartonos-MacBook-Air:AI-Smart-Mirror-master hartono$ python bot.py
/Users/hartono/Documents/AI-Smart-Mirror/AI-Smart-Mirror-master/hhsmartmirror/lib/python2.7/site-packages/pydub/utils.py:178: RuntimeWarning: Couldn't find ffplay or avplay - defaulting to ffplay, but may not work
  warn("Couldn't find ffplay or avplay - defaulting to ffplay, but may not work", RuntimeWarning)
Warning: OpenCV not installed. To use facial recognition, make sure you've properly configured OpenCV.
Found face
Traceback (most recent call last):
  File "bot.py", line 254, in <module>
    bot.start()
  File "bot.py", line 43, in start
    recognizer, audio = self.speech.listen_for_audio()
  File "/Users/hartono/Documents/AI-Smart-Mirror/AI-Smart-Mirror-master/speech.py", line 32, in listen_for_audio
    m = sr.Microphone()
  File "/Users/hartono/Documents/AI-Smart-Mirror/AI-Smart-Mirror-master/hhsmartmirror/lib/python2.7/site-packages/speech_recognition/__init__.py", line 79, in __init__
    self.pyaudio_module = self.get_pyaudio()
  File "/Users/hartono/Documents/AI-Smart-Mirror/AI-Smart-Mirror-master/hhsmartmirror/lib/python2.7/site-packages/speech_recognition/__init__.py", line 110, in get_pyaudio
    raise AttributeError("Could not find PyAudio; check installation")
AttributeError: Could not find PyAudio; check installation
(hhsmartmirror) hartonos-MacBook-Air:AI-Smart-Mirror-master hartono$ python bot.py
/Users/hartono/Documents/AI-Smart-Mirror/AI-Smart-Mirror-master/hhsmartmirror/lib/python2.7/site-packages/pydub/utils.py:178: RuntimeWarning: Couldn't find ffplay or avplay - defaulting to ffplay, but may not work
  warn("Couldn't find ffplay or avplay - defaulting to ffplay, but may not work", RuntimeWarning)
Warning: OpenCV not installed. To use facial recognition, make sure you've properly configured OpenCV.
Found face
Traceback (most recent call last):
  File "bot.py", line 254, in <module>
    bot.start()
  File "bot.py", line 43, in start
    recognizer, audio = self.speech.listen_for_audio()
  File "/Users/hartono/Documents/AI-Smart-Mirror/AI-Smart-Mirror-master/speech.py", line 32, in listen_for_audio
    m = sr.Microphone()
  File "/Users/hartono/Documents/AI-Smart-Mirror/AI-Smart-Mirror-master/hhsmartmirror/lib/python2.7/site-packages/speech_recognition/__init__.py", line 79, in __init__
    self.pyaudio_module = self.get_pyaudio()
  File "/Users/hartono/Documents/AI-Smart-Mirror/AI-Smart-Mirror-master/hhsmartmirror/lib/python2.7/site-packages/speech_recognition/__init__.py", line 110, in get_pyaudio
    raise AttributeError("Could not find PyAudio; check installation")
AttributeError: Could not find PyAudio; check installation

please help me, thanks in advance :)

**Comment by rachnov55** [comment]
seems like you didn't install ffmpeg

**Comment by anggahartono** [comment]
@rachnov55 i do install ffmpeg (ver.4.0) with homebrew

**Comment by brainwane** [comment]
Try upgrading to the latest Python 2.7: https://mail.python.org/pipermail/python-dev/2018-May/153286.html

**Comment by anggahartono** [comment]
@brainwane i update to Python version 2.7.15rc1, but i still got the error..
what should i do then?

**Comment by brainwane** [comment]
A key part of the error you're seeing is:

~~~
The directory '/Users/hartono/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
~~~

Transport Layer Security, or TLS, is part of how we make sure connections between your computer and PyPI are private and secure. It's a cryptographic protocol that's had several versions over time. 

You need to be connecting to PyPI with a TLS support library, such as a recent version of OpenSSL, that supports at least TLS version 1.2. The specific steps you need to take will depend on your operating system version, where your installation of Python originated (python.org, your OS vendor, or an intermediate distributor), and the installed versions of Python, `setuptools`, `pipenv`, and  `pip`. For help, please go to <a href="https://webchat.freenode.net/?channels=%23pypa">the #pypa IRC channel on Freenode</a>, file an issue at <a href="https://github.com/pypa/packaging-problems/issues">pypa/packaging-problems/issues</a>, or <a href="https://www.python.org/community/lists/">post to the python-help mailing list</a>, including:

* where your installation of Python originated (python.org, your OS vendor, or an intermediate distributor)
*  the installed versions of Python, `setuptools`, `wheel` and `pip`
* the output of `pip install --upgrade -vvv pip`

Best wishes.
