### ISSUE TITLE
Cannot Run bot.py on Windows because of ValueError in py4j

### ISSUE THREAD

**Issue by ghost** [HackerHouseYT/AI-Smart-Mirror#88]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "py4j_server\__init__.py", line 34, in launch_py4j_server
    _port = int(_pid.stdout.readline())
ValueError: invalid literal for int() with base 10: ''

**Comment by Josh4you** [comment]
Check if the port number you have entered is correct or not or if its available for p4y to run on.
Check out this page "https://www.py4j.org/py4j_java_gateway.html"
